spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8081

server:
  tomcat:
    threads:
      # 最少线程数
      min-spare: 10
      # 最多线程数
      max: 15
    # 最大连接数
    max-connections: 30
    # 最大等待数
    accept-count: 10
